# This YAML file specifies all settings for Gitpod workspace, including which Docker image to use (hosted somewhere publicly)
# NOTE: In future we may wish to decrease environment spin-up time by creating a public Docker Image with splashkit and other tools preinstalled,
# for now this is beyond scope as we are just trying to get an MVP running

# Docker image (standard gitpod Ubuntu image)
# image: ubuntu:latest

tasks:
  - name: Install skm
    before: bash <(curl -s https://raw.githubusercontent.com/lawrence0arabia/gitpod-splashkit-installer/master/ubuntu-image.sh)
    init: gp sync-done skm_installed
    command: exit
    
  - name: Wait for skm install
    before: gp sync-await skm_installed
    init: sleep 3
    command: gp sync-done skm_done && exit
    openMode: tab-after
    
  - name: Using skm, install splashkit for linux
    init: gp sync-await skm_done
    command: skm linux install
    openMode: tab-after
